name: product_catalog_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  auto_route: ^10.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  validators2: ^5.0.0
  freezed: ^3.0.4 
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  loading_animation_widget: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  flutter_gen_runner: ^5.10.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true 
  
dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.4
  freezed_annotation: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env 

flutter_gen:
  output: lib/gen/ 
  line_length: 80
  integrations:
    flutter_svg: false

    