name: product_catalog_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  validators2: ^5.0.0
  freezed: ^2.4.2 
  flutter_dotenv: ^5.2.1
  http: ^1.3.0

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.4
  freezed_annotation: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env 
    