name: product_catalog_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    

